spring:
  application:
    name: spring-batch
  datasource:
    url: jdbc:mysql://localhost:3307/spring-batch?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      platform: mysql